var arr=new Array();
var arr1=[1,2,3,4,5];
var arr2=['red','vb','bh','bj','hj'];
arr.push(arr1);
console.log(arr);
console.log(arr.length);
arr.push(arr2);
console.log(arr);
console.log(arr.length);
console.log(arr[0].length);